version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:19.8.0
    # working_director: ~/repo
    steps:
      - checkout
      # Download and cache dependencies a
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: cimg/node:19.8.0
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: npm test
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: cimg/node:19.8.0
    steps:
      - run: echo "Say hello to YAML!"
<<<<<<< HEAD

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
=======
>>>>>>> 11a4125c544fe95c84d94874fe2b6b3acfc4a8d4
