version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.8.0

    # working_director: ~/repo

    steps:
      - run: npm install
      - run: npm test
      - run: echo "Say hello to YAML!"
